# Infrastructure Services
# Includes Cloudflare Tunnel, AdGuard Home, Portainer, Homarr, n8n, Watchtower

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    network_mode: host
    # REPLACE with your UUID below
    command: tunnel --no-autoupdate run <TUNNEL_UUID>
    volumes:
      - ./cloudflared:/etc/cloudflared
    security_opt: ["no-new-privileges:true"]
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-pipeline-stages: "timestamp"
        loki-external-labels: "service=cloudflared,environment=homelab"

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    network_mode: host    # bind :53 for DNS
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    security_opt: ["no-new-privileges:true"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/control/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.05'
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-pipeline-stages: "timestamp"
        loki-external-labels: "service=adguardhome,environment=homelab"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    security_opt: ["no-new-privileges:true"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.05'
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-pipeline-stages: "timestamp"
        loki-external-labels: "service=portainer,environment=homelab"

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "7575:7575"
    volumes:
      - ./homarr/configs:/app/data/configs
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt: ["no-new-privileges:true"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7575/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.05'
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-pipeline-stages: "timestamp"
        loki-external-labels: "service=homarr,environment=homelab"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - GENERIC_TIMEZONE=${TZ}
    volumes:
      - ./n8n:/home/node/.n8n
    security_opt: ["no-new-privileges:true"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-pipeline-stages: "timestamp"
        loki-external-labels: "service=n8n,environment=homelab"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=86400  # 24 hours
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - SHOUTRRR_URL=${SHOUTRRR_URL:-}
      - TZ=${TZ}
    command: --label-enable --cleanup --include-stopped --revive-stopped
    security_opt: ["no-new-privileges:true"]
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.05'
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-pipeline-stages: "timestamp"
        loki-external-labels: "service=watchtower,environment=homelab"
