# VPN Services
# Includes Gluetun (ProtonVPN) and qBittorrent routed through VPN

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add: [ NET_ADMIN ]
    devices: [ "/dev/net/tun" ]
    ports:
      - "8080:8080"          # qBittorrent WebUI
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_PROTOCOL=${OPENVPN_PROTOCOL}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      # Optional hardening:
      - FIREWALL_OUTBOUND_SUBNETS=0.0.0.0/0,::/0
      - BLOCK_SURVEILLANCE=on
    # Note: gluetun needs NET_ADMIN capability, so no security_opt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/v1/openvpn/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.05'
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-pipeline-stages: "timestamp"
        loki-external-labels: "service=gluetun,environment=homelab"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on: [ gluetun ]
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - /srv/downloads:/downloads
    security_opt: ["no-new-privileges:true"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/api/v2/app/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-pipeline-stages: "timestamp"
        loki-external-labels: "service=qbittorrent,environment=homelab"
